export const UPDATETEXTFILTER = 'UPDATETEXTFILTER';
export const UPDATEDATEFILTER = 'UPDATEDATEFILTER';
//The 3 date filtering types
export const DATEFILTERALL = 'DATEFILTERALL';
export const DATEFILTERWEEK = 'DATEFILTERWEEK';
export const DATEFILTERYEAR = 'DATEFILTERYEAR';

export const CREATE_EXPENSE = 'CREATE_EXPENSE';
export const CREATE_EXPENSE_REQUEST = 'CREATE_EXPENSE_REQUEST';
export const CREATE_EXPENSE_FAILURE = 'CREATE_EXPENSE_FAILURE';
export const CREATE_EXPENSE_SUCCESS = 'CREATE_EXPENSE_SUCCESS';
export const GET_EXPENSES = 'GET_EXPENSES';
export const GET_EXPENSES_REQUEST = 'GET_EXPENSES_REQUEST';
export const GET_EXPENSES_SUCCESS = 'GET_EXPENSES_SUCCESS';
export const GET_EXPENSES_FAILURE = 'GET_EXPENSES_FAILURE';
