export const UPDATETEXTFILTER = 'UPDATETEXTFILTER';
export const UPDATEDATEFILTER = 'UPDATEDATEFILTER';
//The 3 date filtering types
export const DATEFILTERALL = 'DATEFILTERALL';
export const DATEFILTERWEEK = 'DATEFILTERWEEK';
export const DATEFILTERYEAR = 'DATEFILTERYEAR';

export const CREATE_EXPENSE = 'CREATE_EXPENSE';
export const CREATE_EXPENSE_REQUEST = 'CREATE_EXPENSE_REQUEST';
export const CREATE_EXPENSE_FAILURE = 'CREATE_EXPENSE_FAILURE';
export const CREATE_EXPENSE_SUCCESS = 'CREATE_EXPENSE_SUCCESS';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
